/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shopper2.vista;

import com.shopper2.controlador.ProductoDao;
import com.shopper2.modelo.productos.IAgregarProducto;
import com.shopper2.modelo.productos.Producto;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Angita
 */
public class AgregarProductos extends javax.swing.JFrame {
    
    private IAgregarProducto agregarProducto;
    
      /**
     * Creates new form AgregarProductos
     *
     * @param
     */
    public AgregarProductos(IAgregarProducto agregarProducto) {
        this.agregarProducto = agregarProducto;
        initComponents();
        initProductos();
    }
    
    private void initProductos() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        ArrayList<Producto> productos = ProductoDao.getInstance().obtenerProductos();
        for (Producto producto : productos) {
            model.addElement(producto.getCodpr() + " - " + producto.getNombreProducto());
        }
        boxSeleccionarProducto.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        eSeleccionaProducto = new javax.swing.JLabel();
        boxSeleccionarProducto = new javax.swing.JComboBox<>();
        eCantidad = new javax.swing.JLabel();
        tCantidadProducto = new javax.swing.JTextField();
        bAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGAR PRODUCTOS AL PEDIDO");

        eSeleccionaProducto.setText("SELECCIONA PRODUCTO:");

        eCantidad.setText("INDICA LA CANTIDAD:");

        bAgregar.setText("AGREGAR");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eSeleccionaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxSeleccionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(bAgregar)
                        .addGap(183, 183, 183)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSeleccionaProducto)
                    .addComponent(boxSeleccionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCantidad)
                    .addComponent(tCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(bAgregar)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        int cantidad = Integer.parseInt(tCantidadProducto.getText());
        String selectedItem = (String) boxSeleccionarProducto.getSelectedItem();
        String[] parts = selectedItem.split(" - ");
        int codpr = Integer.parseInt(parts[0]);
        Producto producto = ProductoDao.getInstance().buscar(codpr);
        if(cantidad >= 0){
            agregarProducto.agregarProducto(producto, cantidad);
            tCantidadProducto.setText(null);
        }else{
            JOptionPane.showMessageDialog(null, "Debes escribir un número positivo");
            tCantidadProducto.setText(null);
        }
            
        
            
            
        
      
    }//GEN-LAST:event_bAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JComboBox<String> boxSeleccionarProducto;
    private javax.swing.JLabel eCantidad;
    private javax.swing.JLabel eSeleccionaProducto;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tCantidadProducto;
    // End of variables declaration//GEN-END:variables
}
