/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shopper2.vista;

import com.shopper2.controlador.PedidoDao;
import com.shopper2.controlador.ProductoDao;
import com.shopper2.controlador.RepartidorDao;
import com.shopper2.modelo.pedido.Pedido;
import com.shopper2.modelo.productos.IAgregarProducto;
import com.shopper2.modelo.productos.IProducto;
import com.shopper2.modelo.productos.Producto;
import com.shopper2.modelo.repartidores.Repartidor;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Map;

/**
 * @author Angita
 */
public class EditarPedido extends javax.swing.JFrame implements IAgregarProducto {

    private int codpe;

    /**
     * Creates new form NuevoPedido
     */
    public EditarPedido(int codpe) {
        this.codpe = codpe;
        initComponents();
        initRepartidores();
        initPedido();
    }

    private void initPedido() {
        Pedido pedido = PedidoDao.getInstance().buscar(codpe);
        tNombreCliente.setText(pedido.getNomCliente());
        tDireccionCliente.setText(pedido.getDireccionCliente());
        tFechaPedido.setText(String.valueOf(pedido.getFecha()));
        int elementosBox = boxRepartidores.getItemCount();
        for (int i = 0; i < elementosBox; i++) {
            String elemento = boxRepartidores.getItemAt(i);
            String[] parts = elemento.split(" - ");
            int codr = Integer.parseInt(parts[0]);
            if (codr == pedido.getRepartidor().getCodr()) {
                boxRepartidores.setSelectedIndex(i);
                break;
            }
        }

        for (Map.Entry<IProducto, Integer> entrada : pedido.getProductos().entrySet()) {
            DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
            Object[] datos = new Object[4];
            datos[0] = entrada.getKey().getCodpr();
            datos[1] = entrada.getKey().getNombreProducto();
            datos[2] = entrada.getKey().getCategoria();
            datos[3] = entrada.getValue();
            model.addRow(datos);
        }
    }

    private void initRepartidores() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        ArrayList<Repartidor> repartidores = RepartidorDao.getInstance().obtenerRepartidores();
        for (Repartidor repartidor : repartidores) {
            model.addElement(repartidor.getCodr() + " - " + repartidor.getNomr());
        }
        boxRepartidores.setModel(model);
    }

    public void agregarProducto(Producto producto, int cantidad) {

        if (producto != null) {
            DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
            Object[] datos = new Object[4];
            datos[0] = producto.getCodpr();
            datos[1] = producto.getNombreProducto();
            datos[2] = producto.getCategoria();
            datos[3] = cantidad;
            model.addRow(datos);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        eCliente = new javax.swing.JLabel();
        eDireccionCliente = new javax.swing.JLabel();
        eFechaPedido = new javax.swing.JLabel();
        eCodRepartidor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        bAddProducto = new javax.swing.JButton();
        bDelProducto = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tNombreCliente = new javax.swing.JTextField();
        tDireccionCliente = new javax.swing.JTextField();
        tFechaPedido = new javax.swing.JTextField();
        boxRepartidores = new javax.swing.JComboBox<>();
        etiquetaEjemploFormatoFecha = new javax.swing.JLabel();
        eFormatoFecha = new javax.swing.JLabel();
        bModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDITAR PEDIDO");

        panel.setName("NUEVO PEDIDO"); // NOI18N

        eCliente.setText("NOMBRE CLIENTE");

        eDireccionCliente.setText("DIRECCIÓN CLIENTE");

        eFechaPedido.setText("FECHA PEDIDO");

        eCodRepartidor.setText("ID REPARTIDOR");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "CATEGORIA", "CANTIDAD"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        bAddProducto.setText("AGREGAR PRODUCTO");
        bAddProducto.setToolTipText("");
        bAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddProductoActionPerformed(evt);
            }
        });

        bDelProducto.setText("BORRAR PRODUCTO");
        bDelProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelProductoActionPerformed(evt);
            }
        });

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tFechaPedido.setToolTipText("AAAA-MM-DD");

        etiquetaEjemploFormatoFecha.setText("Ejemplo: 2023-12-01");

        eFormatoFecha.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        eFormatoFecha.setText("AAAA-MM-DD ");

        bModificar.setText("MODIFICAR");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(bModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eCodRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eFechaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eDireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tNombreCliente)
                            .addComponent(tDireccionCliente)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eFormatoFecha)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(tFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(etiquetaEjemploFormatoFecha)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAddProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCliente)
                    .addComponent(tNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDireccionCliente)
                    .addComponent(tDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eFechaPedido)
                    .addComponent(tFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaEjemploFormatoFecha))
                .addGap(2, 2, 2)
                .addComponent(eFormatoFecha)
                .addGap(5, 5, 5)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCodRepartidor)
                    .addComponent(boxRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(bAddProducto)
                        .addGap(92, 92, 92)
                        .addComponent(bDelProducto)))
                .addGap(34, 34, 34)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar)
                    .addComponent(bModificar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddProductoActionPerformed
        AgregarProductos agregarProductos = new AgregarProductos(this);
        agregarProductos.setVisible(true);
    }//GEN-LAST:event_bAddProductoActionPerformed

    private void bDelProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelProductoActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Obtener el valor de la columna 0 (suponiendo que sea la columna primaria)
            int productoId = (int) model.getValueAt(filaSeleccionada, 0);

            // Eliminar la fila seleccionada del modelo de tabla
            model.removeRow(filaSeleccionada);

            // Eliminar el producto de la base de datos utilizando el ID
            ProductoDao.getInstance().eliminar(productoId);
        }
    }//GEN-LAST:event_bDelProductoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        ListaPedidos listaPedidos = new ListaPedidos();
        listaPedidos.setVisible(true);
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        //Objeto de tipo Pedido para recoger la información introducida por el usuario
        Pedido pedido = new Pedido();
        pedido.setCodpe(codpe);
        //Almacenamiento del dato nombre del cliente
        pedido.setNomCliente(tNombreCliente.getText());
        //Almacenamiento del dato dirección del cliente
        pedido.setDireccionCliente(tDireccionCliente.getText());
        //Almacenamiento del dato fecha del pedido
        pedido.setFecha(Date.valueOf(tFechaPedido.getText()));
        //Almacenamiento del dato repartidor
        String selectedItem = (String) boxRepartidores.getSelectedItem();
        String[] parts = selectedItem.split(" - ");
        int codr = Integer.parseInt(parts[0]);
        Repartidor repartidor = RepartidorDao.getInstance().buscar(codr);
        pedido.setRepartidor(repartidor);



        if (PedidoDao.getInstance().modificar(pedido)) {
            ListaPedidos pedidos = new ListaPedidos();
            pedidos.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_bModificarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddProducto;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bDelProducto;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> boxRepartidores;
    private javax.swing.JLabel eCliente;
    private javax.swing.JLabel eCodRepartidor;
    private javax.swing.JLabel eDireccionCliente;
    private javax.swing.JLabel eFechaPedido;
    private javax.swing.JLabel eFormatoFecha;
    private javax.swing.JLabel etiquetaEjemploFormatoFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tDireccionCliente;
    private javax.swing.JTextField tFechaPedido;
    private javax.swing.JTextField tNombreCliente;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
