/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shopper2.vista;

import com.shopper2.controlador.MenuPrincipalControlador;

public class MenuPrincipal extends javax.swing.JFrame {

    MenuPrincipalControlador controlador;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(MenuPrincipalControlador controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        bNuevoPedido = new javax.swing.JButton();
        bVerPedidos = new javax.swing.JButton();
        eAppShopper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");

        panel.setBackground(new java.awt.Color(204, 204, 255));
        panel.setName("APP SHOPPER"); // NOI18N

        bNuevoPedido.setBackground(new java.awt.Color(0, 0, 153));
        bNuevoPedido.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bNuevoPedido.setForeground(new java.awt.Color(255, 255, 255));
        bNuevoPedido.setText("NUEVO PEDIDO");
        bNuevoPedido.setToolTipText("");
        bNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoPedidoActionPerformed(evt);
            }
        });

        bVerPedidos.setBackground(new java.awt.Color(0, 0, 153));
        bVerPedidos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bVerPedidos.setForeground(new java.awt.Color(255, 255, 255));
        bVerPedidos.setText("VER PEDIDOS");
        bVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerPedidosActionPerformed(evt);
            }
        });

        eAppShopper.setFont(new java.awt.Font("Consolas", 3, 24)); // NOI18N
        eAppShopper.setForeground(new java.awt.Color(51, 0, 204));
        eAppShopper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eAppShopper.setIcon(new javax.swing.ImageIcon("C:\\Users\\Angita\\IdeaProjects\\Shopper2\\shopper.png")); // NOI18N
        eAppShopper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eAppShopper.setName(""); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bVerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNuevoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addGap(75, 75, 75))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(eAppShopper, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(eAppShopper, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bNuevoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(bVerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoPedidoActionPerformed
        controlador.abrirNuevoPedido();
        dispose();
    }//GEN-LAST:event_bNuevoPedidoActionPerformed

    private void bVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerPedidosActionPerformed
        controlador.abrirListaPedidos();
        dispose();
    }//GEN-LAST:event_bVerPedidosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNuevoPedido;
    private javax.swing.JButton bVerPedidos;
    private javax.swing.JLabel eAppShopper;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
