create table repartidores(codr INTEGER primary key AUTOINCREMENT, nomr TEXT)

insert into repartidores (nomr) values ('manuel'), ('ricardo'), ('sara')

create table pedidos (codpe INTEGER primary key AUTOINCREMENT, nomCliente TEXT, direccion TEXT, fecha DATE, codr INTEGER, foreign key (codr) references repartidores (codr))

create table productos (codpr INTEGER primary key AUTOINCREMENT, nompr TEXT, categoria TEXT)

insert into productos (nompr, categoria) values ('platano', 'alimentacion'),
								('manzana', 'alimentacion'),
								('pera', 'alimentacion'),
								('naranja', 'alimentacion'),
								('kiwi', 'alimentacion'),
								('yogur', 'alimentacion'),
								('chorizo', 'alimentacion'),
								('jamon', 'alimentacion'),
								('queso', 'alimentacion'),
								('macarrones', 'alimentacion'),
								('berberechos', 'alimentacion'),
								('mortadela', 'alimentacion'),
								('espaguetis', 'alimentacion'),
								('leche', 'alimentacion'),
								('colacao', 'alimentacion'),
								('melon', 'alimentacion'),
								('sandia', 'alimentacion'),
								('mandarina', 'alimentacion'),
								('carne', 'alimentacion'),
								('pescado', 'alimentacion'),
								('chocolate', 'alimentacion'),
								('galleta', 'alimentacion'),
								('pan', 'alimentacion'),
								('agua', 'alimentacion'),
								('cocacola', 'alimentacion'),
								('fanta', 'alimentacion'),
								('vino', 'alimentacion'),
								('cerveza', 'alimentacion'),
								('pizza', 'alimentacion'),
								('limon', 'alimentacion'),
								('cepillo de dientes', 'higiene'),
								('jabon', 'higiene'),
								('pasta de dientes', 'higiene'),
								('acondicionador', 'higiene'),
								('tampon', 'higiene'),
								('compresa', 'higiene'),
								('cepillo', 'higiene'),
								('peine', 'higiene'),
								('hilo dental', 'higiene'),
								('cortauñas', 'higiene'),
								('pinza', 'higiene'),
								('tijeras', 'higiene'),
								('enjuague bucal', 'higiene'),
								('papel higienico', 'higiene'),
								('toallitas', 'higiene'),
								('colonia', 'drogueria'),
								('perfume', 'drogueria'),
								('desodorante', 'drogueria'),
								('champu', 'drogueria'),
								('gel de ducha', 'drogueria'),
								('agua micelar', 'drogueria'),
								('crema hidratante', 'drogueria'),
								('protector solar', 'drogueria'),
								('repelente', 'drogueria'),
								('vitaminas', 'drogueria'),
								('gomina', 'drogueria'),
								('crema antiarrugas', 'drogueria'),
								('balsamo', 'drogueria'),
								('esmalte', 'drogueria'),
								('quitaesmalte', 'drogueria'),
								('plantillas', 'drogueria'),
								('tiritas', 'drogueria'),
								('algodon', 'drogueria'),
								('termometro', 'drogueria'),
								('agua oxigenada', 'drogueria'),
								('detergente', 'drogueria'),
								('desinfectante', 'drogueria'),
								('ambientador', 'drogueria'),
								('lejia', 'drogueria'),
								('pilas', 'drogueria'),
								('bolsa de basura', 'drogueria'),
								('pienso perro', 'mascotas'),
								('pienso gato', 'mascotas'),
								('bebedero', 'mascotas'),
								('comedero', 'mascotas'),
								('collar', 'mascotas'),
								('correa', 'mascotas'),
								('arnes', 'mascotas'),
								('cama', 'mascotas'),
								('jaula', 'mascotas'),
								('transportador', 'mascotas'),
								('calcetines', 'mascotas'),
								('rascador', 'mascotas'),
								('bozal', 'mascotas'),
								('arena', 'mascotas'),
								('cepillo para mascotas', 'mascotas'),
								('champu para perros', 'mascotas'),
								('champu para gatos', 'mascotas'),
								('bolsa para excrementos', 'mascotas'),
								('champu antipulgas', 'mascotas'),
								('juguete', 'mascotas')

create table tienen (codpe integer, codpr integer, cantidad integer, primary key (codpe, codpr), foreign key (codpe) references pedidos (codpe), foreign key (codpr) references productos (codpr));